### ISSUE TITLE
请教您build Setup

### ISSUE THREAD

**Issue by leonbaichi** [xrr2016/vue-express-mongodb#11]
感谢您的文章，对我初学很有帮助！！！想咨询您下，您给出的Build Setup
1-- install dependencies
npm install
2-- serve with hot reload at localhost:8080
npm run dev
3-- build for production with minification
npm run build
4-- build for production and view the bundle analyzer report
npm run build --report
5-- 后端开发 localhost:3000
npm run server
6-- webpack打包后,后端运行express静态目录'dist'
npm run start

我能理解1,3,6步，请教您下2,4,5步是不是必须的？
第2步是为了使用webpack-dev-server进行hot reload吗？
我进行到第2步，浏览器会自动打开localhost:8080,并报一个错误
**proxy request /api/movie from localhost:8080 to http://localhost:3000**
第5步是为了检查到代码变化，自动重启node？

**Comment by xrr2016** [comment]
感谢你的反馈,.
1. 第2步是为了开发前端起的服务, 是必须的;
2. 第4步不是必须的;
3. 那个不是错误, 目的是为了将8080端口的请求代理到3000端口, 实现前后对接;
4. 是的.
