### ISSUE TITLE
代码不完整啊

### ISSUE THREAD

**Issue by chounvwudi** [xrr2016/vue-express-mongodb#13]
跑不出你贴的动图的效果，找不到入口

**Comment by xrr2016** [comment]
你把报错信息放上来啊。

**Comment by chounvwudi** [comment]
没有报错，只是不知道访问的入口地址，访问http://localhost:8080和http://localhost:3000只显示vue.js的欢迎界面，并没有你动图的界面

**Comment by xrr2016** [comment]
你先用  git clone 命令把代码克隆下来才行.

**Comment by chounvwudi** [comment]
是克隆下来的，也执行了 npm install ，run之后就只有vue.js的欢迎界面
