### ISSUE TITLE
关于node服务的根路由问题

### ISSUE THREAD

**Issue by gethin94** [xrr2016/vue-express-mongodb#22]
```
app.use(favicon(__dirname + '/src/assets/favicon.ico'))
app.use(express.static('dist'))
app.use('/',index)
app.use('/api',movie)
````

这段代码：如果`npm run build`，就会首先执行`app.use(express.static('dist'))`，就会渲染HTML页面；如果没有`npm run build`，就是走`app.use('/',index)`，走根路由。
可以这样理解嘛。
`app.use(express.static('dist'))`，他是怎么渲染HTML的呢。
**还有人在吗，求大佬回应一下**

**Comment by xrr2016** [comment]
> ```
> app.use(favicon(__dirname + '/src/assets/favicon.ico'))
> app.use(express.static('dist'))
> app.use('/',index)
> app.use('/api',movie)
> ```
> 
> 这段代码：如果`npm run build`，就会首先执行`app.use(express.static('dist'))`，就会渲染HTML页面；如果没有`npm run build`，就是走`app.use('/',index)`，走根路由。
> 可以这样理解嘛。
> `app.use(express.static('dist'))`，他是怎么渲染HTML的呢。
> **还有人在吗，求大佬回应一下**

`app.use(express.static('dist'))` 这段代码就是让 express 使用前端 Vue 项目构建出来的静态文件而已，前端项目生成 dist 目录里面就是要渲染的页面

**Comment by gethin94** [comment]
@xrr2016 谢谢解答，刚刚也可看到类似的文章
> 现在就可以访问http://localhost:8080，它会在浏览器中打开当前目录的public子目录（严格来说，是打开public目录的index.html文件）。如果public目录之中有一个图片文件my_image.png，那么可以用http://localhost:8080/my_image.png访问该文件。

[Express框架](http://javascript.ruanyifeng.com/nodejs/express.html#toc0)
