### ISSUE TITLE
seo 与 前后端分离

### ISSUE THREAD

**Issue by shengzhong2258** [xrr2016/vue-express-mongodb#3]
重seo，如何处理

**Comment by xrr2016** [comment]
重SEO的话就要用后端渲染的方式了,因为爬虫不会执行js,参考这篇文章[ 前端渲染与SEO优化踩坑小记](https://segmentfault.com/a/1190000006756585#articleHeader0);
或者可以尝试使用[vue-head](https://github.com/ktquez/vue-head).
