### ISSUE TITLE
关于index.html

### ISSUE THREAD

**Issue by hezhongfeng** [xrr2016/vue-express-mongodb#4]
你好：
有个问题想咨询下
前端生成后是一个index.html和一些用到的js、css
然后在服务器端把前端生成的index.html等设置成静态资源给用户访问
那么用户怎么访问？URL应该是直接指向这个index.html的吧？不然也没有资源供用户访问
访问index.html之后才能利用前端路由对URL进行拦截处理
我的理解是对的吗？

**Comment by xrr2016** [comment]
对,将dist作为express的静态目录后,用户通过url访问服务器域名,然后通多DNS解析到服务器的地址上,服务器返回html文件,也就是dist/index.html.
Vuejs的前端路由就是href里面'#'后面的东西,跟服务器的router没有关系的,其实就是一张页面,通过ajax获取数据,大致可以这么理解,可以看看vue-router的文档加深理解.

**Comment by hezhongfeng** [comment]
我感觉你没懂我的问题，我了解前端和后端路由
我的意思是作为静态文件的话，必须是指出什么文件才能访问的
所以必须得访问`/index.html`这样吗？

**Comment by xrr2016** [comment]
恩, express.static中间件将你设置为参数的目录, 作为提供访问静态资源的目录, 通过相对路径访问需要的文件.

**Comment by hezhongfeng** [comment]
Thanks.
