### ISSUE TITLE
vue和react的问题

### ISSUE THREAD

**Issue by tigaly** [xrr2016/vue-express-mongodb#7]
首先赞美博主，看你的例子帮助我解决不少疑惑

其次博主有没有关注过dva和antd，我感觉前后端分离的话，就直接开一个express跑rest server，再另开一个前端项目更好？（其实我主要觉得antd的组件好抄。。。）

**Comment by xrr2016** [comment]
感谢你的反馈, 能解决你的困惑我很开心.
dva相当于react的最佳实践吧, 让新手们学react少踩坑, 因为react自由度高, 但是也容易写bug, 不过我觉得还是自己学习react才能领会react的 '抽象', 学了之后成就感可能会更高吧...
对的, 前端项目还是跟后端的分开比较好, 解构更加清晰.

**Comment by tigaly** [comment]
@xrr2016 嗯，我angular2和react都是半桶水，感觉这两个都挺好，vue没研究过，有空看看

顺带问一个问题，express现在还是用回调来解决同步异步的问题，而现在主流都是用async，promise这些，你怎么看呢？

**Comment by xrr2016** [comment]
javascript 本身是单线程的, 回调函数应该是效率最高的方式, async 以及 promise 解决的是回调函数的 '控制翻转'问题, 同时让代码更符合阅读习惯, 写代码的更加方便, 肯定是极大的进步.
