### ISSUE TITLE
mongodb的问题

### ISSUE THREAD

**Issue by FateZeros** [xrr2016/vue-express-mongodb#8]
按照你的项目搭建了环境，postman怎么接口调用返回空？

db.Movie.find()
{ 
  "_id" : ObjectId("58ec4311669dabc9f105d7ea"),
  "title" : "黑夜传说", 
  "poster" : "12", 
  "rating" : "5.4", 
  "introduction" : "不错不错",
 "created_at" : "201706317", 
 "update_at" : "2017291" 
}

**Comment by xrr2016** [comment]
...把代码贴出来啊

**Comment by FateZeros** [comment]
git clone 你的代码啊，自己去安装了mongodb，但是接口返回[]

**Comment by xrr2016** [comment]
可能你的 mongodb 服务没启动,要先启动才行

**Comment by FateZeros** [comment]
能加我QQ么 490293266 想详细咨询下你....
